### ISSUE TITLE
possible bug in split.py 

### ISSUE THREAD

**Issue by EugenEvgeny** [LukasHedegaard/office31#1] opened 2021-03-21 03:19 UTC
I got some errors running the example with modified "office_path" argument. 
I have been able to fix this issue by replacing the "OFFICE_PATH" by "office_path" in lines 50 and 52 of the split.py file.

**Comment by LukasHedegaard** [comment] 2021-03-30 12:11
Hi Eugen, thanks for bringing this to my attention.
The issue is fixed in PR #2

**Closed as completed** 2021-03-30 12:14 UTC
